services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: solar-planner-dev
    volumes:
      - ./.dev-config:/config
      - ./custom_components/solar_planner_scheduler:/config/custom_components/solar_planner_scheduler
    ports:
      - "8123:8123"
    restart: unless-stopped
